import { Router, Response, NextFunction } from "express";
import { asyncMiddleware } from "middleware-async";
import auth, { Request_extended } from "../middlewares/auth.js";
import list from "./list.js";
import doc from "./doc.js";
const api = Router();
api.use(asyncMiddleware(auth));
api.use("/list", list);
api.use("/doc", doc);
export default api;
